Make test tools optional

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -15,11 +15,18 @@ NC='\033[0m'
 
 declare -A tools=()
 declare -A desired=()
+declare -A skip=()
 
 for arg in "$@"; do
   case ${arg%%=*} in
     "--with-go")
       desired[go]="${arg##*=}"
+      ;;
+    "--without-ginkgo")
+      skip[ginkgo]="-"
+      ;;
+    "--without-linter")
+      skip[golangci-lint]="-"
       ;;
     "--help")
       printf "${GREEN}$0${NC}\n"
@@ -84,37 +91,45 @@ check_go_version() {
   esac
 
   echo -n "Checking ginkgo version... "
-  GINKGO_VERSION=$(${tools[ginkgo]} version | ${tools[awk]} '{print $3}')
-  vercomp $GINKGO_VERSION 1.10
-  case $? in
-    0) ;&
-    1)
-      printf "${GREEN}"
-      echo $GINKGO_VERSION
-      printf "${NC}"
-      ;;
-    2)
-      printf "${RED}"
-      echo "$GINKGO_VERSION < 1.10"
-      exit 1
-      ;;
-  esac
+  if ! [ -z "${skip[ginkgo]}" ]; then
+    printf "${BLUE}skipped${NC}\n"
+  else
+    GINKGO_VERSION=$(${tools[ginkgo]} version | ${tools[awk]} '{print $3}')
+    vercomp $GINKGO_VERSION 1.10
+    case $? in
+      0) ;&
+      1)
+        printf "${GREEN}"
+        echo $GINKGO_VERSION
+        printf "${NC}"
+        ;;
+      2)
+        printf "${RED}"
+        echo "$GINKGO_VERSION < 1.10"
+        exit 1
+        ;;
+    esac
+  fi
 }
 
 check_for() {
   echo -n "Checking for $1... "
-  if ! [ -z "${desired[$1]}" ]; then
-    TOOL_PATH="${desired[$1]}"
+  if ! [ -z "${skip[$1]}" ]; then
+    printf "${BLUE}skipped${NC}\n"
   else
-    TOOL_PATH=$(command -v $1)
-  fi
-  if ! [ -x "$TOOL_PATH" -a -f "$TOOL_PATH" ]; then
-    printf "${RED}not found${NC}\n"
-    cd - > /dev/null
-    exit 1
-  else
-    printf "${GREEN}found${NC}\n"
-    tools[$1]=$TOOL_PATH
+    if ! [ -z "${desired[$1]}" ]; then
+      TOOL_PATH="${desired[$1]}"
+    else
+      TOOL_PATH=$(command -v $1)
+    fi
+    if ! [ -x "$TOOL_PATH" -a -f "$TOOL_PATH" ]; then
+      printf "${RED}not found${NC}\n"
+      cd - > /dev/null
+      exit 1
+    else
+      printf "${GREEN}found${NC}\n"
+      tools[$1]=$TOOL_PATH
+    fi
   fi
 }
 
